export default function Head() {
    return (
      <>
        <title>Sobre mim</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css"
        />
        <link rel="icon" href="/favicon.ico" />
      </>
    );
  }
  