export default function Head() {
  return (
    <>
      <title>JM Dev BR</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta name="google-site-verification" content="KQbKUkqyk4EpzZW5mapukLWwK4kuwYb-MasGz0sn6C8" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
