# name: Deploy to VPS

# on: [push]

# jobs:
#   build:
#     runs-on: ubuntu-latest  
#     steps:
#         uses: actions/checkout@v2
#       - name: Checkout code
#       - name: Set up SSH
#         uses: easingthemes/ssh-deploy@main
#         env:
#           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#           ARGS: "-rltgoDzvO"
#           SOURCE: "src/"
#           REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#           REMOTE_USER: ${{ secrets.REMOTE_USER }}
#           REMOTE_PORT: ${{secrets.REMOTE_PORT}}
#           TARGET: ${{ secrets.REMOTE_TARGET }}
#           EXCLUDE: "/dist/, /node_modules/"
name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{secrets.REMOTE_PORT}}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/dist/, /node_modules/"
    # - name: Install npm dependencies
    #   run: npm install --force
    # - name: Run build task
    #   run: npm run build --if-present
    - name: Start PM2 Application
      run: |
        cat ${{ secrets.SSH_PRIVATE_KEY }}
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} -p ${{ secrets.REMOTE_PORT }} "mkdir testando_comando"
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} -p ${{ secrets.REMOTE_PORT }} "npm install"

 
#       ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} -p ${{ secrets.REMOTE_PORT }} "pm2 start npm --name portfolio -- start" 