name: Node CI

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
#     - name: Install Node.js
#       uses: actions/setup-node@v1
#       with:
#         node-version: '16.x'
#     - name: Deploy to Server
#       uses: easingthemes/ssh-deploy@main
#       env:
#           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#           ARGS: "-rltgoDzvO --delete"
#           SOURCE: "./"
#           REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#           REMOTE_USER: ${{ secrets.REMOTE_USER }}
#           REMOTE_PORT: ${{secrets.REMOTE_PORT}}
#           TARGET: ${{ secrets.REMOTE_TARGET }}
#           EXCLUDE: "/dist/, /node_modules/"
    - name: Pull Changes Of Remote Repository
      run: git pull origin main
    - name: Build and Initialize
      run: "npm install && npm run build && npm start"
